"""
Simple TinyML Model Verification Script (Python)

This script:
  1. Loads the .tflite model
  2. Creates test input data
  3. Runs inference
  4. Saves test data for C comparison

Author: TinyML Code Helper
Date: 2026-03-27
"""

import os
import numpy as np
import tensorflow as tf
from typing import Tuple


def verify_model(tflite_path: str, output_dir: str = ".") -> Tuple[np.ndarray, np.ndarray]:
    """
    Load TFLite model, run inference, and save test data.
    
    Creates deterministic test input and runs inference with the TFLite model.
    Saves the test data for comparison with C implementation.
    
    Args:
        tflite_path: Path to the .tflite file
        output_dir: Directory to save test data files
        
    Returns:
        Tuple of (test_input, inference_output)
    """
    print("\n" + "="*60)
    print("TinyML Model Verification (Python)")
    print("="*60)
    
    # Load TFLite model
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    
    # Get input/output details
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    print(f"\n📋 Model Information:")
    print(f"   Input shape: {input_details[0]['shape']}")
    print(f"   Input dtype: {input_details[0]['dtype']}")
    print(f"   Output shape: {output_details[0]['shape']}")
    print(f"   Output dtype: {output_details[0]['dtype']}")
    
    # Expected shape: (1, 50, 3) for batch_size=1, timesteps=50, features=3
    expected_shape = input_details[0]['shape']
    timesteps = expected_shape[1]
    features = expected_shape[2]
    
    # Create deterministic test input
    # Using a simple pattern that's easy to recreate in C
    print(f"\n🔢 Creating test input ({timesteps} timesteps * {features} features)...")
    test_input = np.zeros((1, timesteps, features), dtype=np.int8)
    
    for i in range(timesteps):
        # Create a simple, reproducible pattern
        test_input[0, i, 0] = (i % 128) - 64          # x-axis: -64 to +63
        test_input[0, i, 1] = ((i * 2) % 128) - 64    # y-axis: different pattern
        test_input[0, i, 2] = ((i * 3) % 128) - 64    # z-axis: different pattern
    
    print(f"   ✅ Test input created")
    print(f"   Sample values (first 3 timesteps):")
    for i in range(min(3, timesteps)):
        print(f"      t={i}: x={test_input[0, i, 0]:4d}, "
              f"y={test_input[0, i, 1]:4d}, z={test_input[0, i, 2]:4d}")
    
    # Run inference
    print(f"\n🚀 Running Python inference...")
    interpreter.set_tensor(input_details[0]['index'], test_input)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])
    
    print(f"\n📊 Python Inference Results:")
    print(f"   Raw output: {output[0]}")
    print(f"   Class 0 (Wave) score: {output[0][0]:4d}")
    print(f"   Class 1 (Idle) score: {output[0][1]:4d}")
    
    # Determine prediction
    predicted_class = np.argmax(output[0])
    class_names = ['Wave', 'Idle']
    print(f"   Predicted class: {predicted_class} ({class_names[predicted_class]})")
    
    # Save test data for C comparison
    test_input_file = os.path.join(output_dir, "test_input.npy")
    expected_output_file = os.path.join(output_dir, "expected_output.npy")
    
    np.save(test_input_file, test_input)
    np.save(expected_output_file, output)
    
    print(f"\n💾 Test data saved:")
    print(f"   Input:  {test_input_file}")
    print(f"   Output: {expected_output_file}")
    
    # Also save as CSV for easy C reading
    test_input_csv = os.path.join(output_dir, "test_input.csv")
    with open(test_input_csv, 'w') as f:
        f.write("# Test input data for C verification\n")
        f.write("# Format: timestep, x, y, z\n")
        for i in range(timesteps):
            f.write(f"{i},{test_input[0, i, 0]},{test_input[0, i, 1]},{test_input[0, i, 2]}\n")
    
    print(f"   CSV:    {test_input_csv} (for C program)")
    
    # Create a C header with the test data
    test_data_h = os.path.join(output_dir, "test_data.h")
    with open(test_data_h, 'w') as f:
        f.write("// Auto-generated test data for C verification\n")
        f.write("// Generated by verify_model.py\n\n")
        f.write("#ifndef TEST_DATA_H\n")
        f.write("#define TEST_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define TEST_TIMESTEPS {timesteps}\n")
        f.write(f"#define TEST_FEATURES {features}\n\n")
        f.write("// Test input data: [timesteps][features]\n")
        f.write("const int8_t test_input[TEST_TIMESTEPS][TEST_FEATURES] = {\n")
        for i in range(timesteps):
            f.write(f"    {{{test_input[0, i, 0]:4d}, {test_input[0, i, 1]:4d}, {test_input[0, i, 2]:4d}}}")
            f.write(",\n" if i < timesteps - 1 else "\n")
        f.write("};\n\n")
        f.write("// Expected output from Python inference\n")
        f.write(f"const int8_t expected_output[2] = {{{output[0][0]}, {output[0][1]}}};\n\n")
        f.write("#endif  // TEST_DATA_H\n")
    
    print(f"   Header: {test_data_h} (can #include in C program)")
    
    return test_input, output


def main() -> bool:
    """Main verification workflow."""
    
    # File paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    tflite_path = os.path.join(script_dir, "..", "models", "magic_wand_model.tflite")
    
    # Check if model exists
    if not os.path.exists(tflite_path):
        print(f"\n❌ ERROR: TFLite file not found: {tflite_path}")
        print("   Make sure you've run Phase_1/optimize_model.py first")
        return False
    
    # Run verification
    try:
        test_input, output = verify_model(tflite_path, script_dir)
        print("\n✅ Verification complete!")
        return True
    except Exception as e:
        print(f"\n❌ ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
